export const LEMMA_FAMILIES: Record<string, string[]> = {
  lend: ["lend", "lends", "lent", "lending"],
  borrow: ["borrow", "borrows", "borrowed", "borrowing"],
  make: ["make", "makes", "made", "making"],
  do: ["do", "does", "did", "done", "doing"],
  bring: ["bring", "brings", "brought", "bringing"],
  take: ["take", "takes", "took", "taken", "taking"],
  lose: ["lose", "loses", "lost", "losing"],
  miss: ["miss", "misses", "missed", "missing"],
  say: ["say", "says", "said", "saying"],
  tell: ["tell", "tells", "told", "telling"],
  hear: ["hear", "hears", "heard", "hearing"],
  listen: ["listen", "listens", "listened", "listening"],
  go: ["go", "goes", "went", "gone", "going"],
  come: ["come", "comes", "came", "coming"],
  get: ["get", "gets", "got", "gotten", "getting"],
  see: ["see", "sees", "saw", "seen", "seeing"],
  look: ["look", "looks", "looked", "looking"],
  watch: ["watch", "watches", "watched", "watching"],
  speak: ["speak", "speaks", "spoke", "spoken", "speaking"],
  talk: ["talk", "talks", "talked", "talking"],
  know: ["know", "knows", "knew", "known", "knowing"],
  learn: ["learn", "learns", "learned", "learnt", "learning"],
  find: ["find", "finds", "found", "finding"],
  have: ["have", "has", "had", "having"],
  work: ["work", "works", "worked", "working"],
  rent: ["rent", "rents", "rented", "renting"],
  hire: ["hire", "hires", "hired", "hiring"],
};
