-- Body packs lexicon import (daily + precise)
-- Idempotent inserts: lexicon_entries, lexicon_senses, lexicon_translations, lexicon_examples

begin;

with words(lemma, lemma_norm, pos, definition_en, translation_pl, example_en, example_pl, order_index) as (
  values
    ('head', 'head', 'noun', 'the upper part of the body', 'głowa', 'My head hurts today.', 'Dziś boli mnie głowa.', 1),
    ('face', 'face', 'noun', 'the front part of the head', 'twarz', 'Her face looks tired.', 'Jej twarz wygląda na zmęczoną.', 2),
    ('hair', 'hair', 'noun', 'the strands growing on the head', 'włosy', 'His hair is wet.', 'Jego włosy są mokre.', 3),
    ('forehead', 'forehead', 'noun', 'the part above the eyes', 'czoło', 'She touched her forehead.', 'Dotknęła swojego czoła.', 4),
    ('eye', 'eye', 'noun', 'the organ of sight', 'oko', 'My eye is red.', 'Moje oko jest czerwone.', 5),
    ('ear', 'ear', 'noun', 'the organ of hearing', 'ucho', 'He has an earache.', 'Ma ból ucha.', 6),
    ('nose', 'nose', 'noun', 'the organ used for breathing and smelling', 'nos', 'My nose is cold.', 'Mój nos jest zimny.', 7),
    ('mouth', 'mouth', 'noun', 'the opening used to eat and speak', 'usta', 'Open your mouth, please.', 'Otwórz usta, proszę.', 8),
    ('lip', 'lip', 'noun', 'the edge of the mouth', 'warga', 'She bit her lip.', 'Przygryzła wargę.', 9),
    ('cheek', 'cheek', 'noun', 'the side of the face', 'policzek', 'He kissed her cheek.', 'Pocałował ją w policzek.', 10),
    ('tooth', 'tooth', 'noun', 'a hard structure in the mouth', 'ząb', 'This tooth hurts.', 'Ten ząb boli.', 11),
    ('tongue', 'tongue', 'noun', 'the muscle in the mouth', 'język', 'He burned his tongue.', 'Oparzył sobie język.', 12),
    ('chin', 'chin', 'noun', 'the lower part of the face', 'broda', 'He has a strong chin.', 'Ma mocną brodę.', 13),
    ('facial hair', 'facial hair', 'noun', 'hair growing on the face', 'zarost', 'Facial hair grows fast.', 'Zarost rośnie szybko.', 14),
    ('torso', 'torso', 'noun', 'the main part of the body without limbs', 'tułów', 'The torso is strong.', 'Tułów jest silny.', 15),
    ('chest', 'chest', 'noun', 'the front of the upper body', 'klatka piersiowa', 'He felt pain in his chest.', 'Poczuł ból w klatce piersiowej.', 16),
    ('back', 'back', 'noun', 'the rear part of the body', 'plecy', 'My back is sore.', 'Bolą mnie plecy.', 17),
    ('neck', 'neck', 'noun', 'the part connecting head and body', 'szyja', 'She wears a scarf on her neck.', 'Nosi szalik na szyi.', 18),
    ('belly', 'belly', 'noun', 'the front of the body between chest and hips', 'brzuch', 'My belly feels full.', 'Mój brzuch jest pełny.', 19),
    ('waist', 'waist', 'noun', 'the narrow middle part of the body', 'talia', 'The belt sits on the waist.', 'Pasek leży na talii.', 20),
    ('hip', 'hip', 'noun', 'the side of the body above the leg', 'biodro', 'She hurt her hip.', 'Uraziła sobie biodro.', 21),
    ('shoulder', 'shoulder', 'noun', 'the joint connecting arm to body', 'bark', 'He carried the bag on his shoulder.', 'Niósł torbę na barku.', 22),
    ('arm', 'arm', 'noun', 'the upper limb from shoulder to hand', 'ramię', 'He raised his arm.', 'Podniósł ramię.', 23),
    ('elbow', 'elbow', 'noun', 'the joint in the middle of the arm', 'łokieć', 'She leaned on her elbow.', 'Oparła się na łokciu.', 24),
    ('wrist', 'wrist', 'noun', 'the joint between hand and arm', 'nadgarstek', 'He wears a watch on his wrist.', 'Nosi zegarek na nadgarstku.', 25),
    ('hand', 'hand', 'noun', 'the part at the end of the arm', 'dłoń', 'Wash your hands.', 'Umyj dłonie.', 26),
    ('finger', 'finger', 'noun', 'a digit on the hand', 'palec', 'He cut his finger.', 'Skaleczył palec.', 27),
    ('nail', 'nail', 'noun', 'the hard covering at the end of a finger', 'paznokieć', 'She painted her nails.', 'Pomalowała paznokcie.', 28),
    ('nipple', 'nipple', 'noun', 'the small part in the center of the breast', 'sutek', 'The baby touched the nipple.', 'Dziecko dotknęło sutka.', 29),
    ('breast', 'breast', 'noun', 'the part on the front of the chest', 'pierś', 'She felt pain in her breast.', 'Poczuła ból w piersi.', 30),
    ('leg', 'leg', 'noun', 'the limb used for walking', 'noga', 'My leg is tired.', 'Moja noga jest zmęczona.', 31),
    ('thigh', 'thigh', 'noun', 'the upper part of the leg', 'udo', 'He has strong thighs.', 'Ma mocne uda.', 32),
    ('knee', 'knee', 'noun', 'the joint between thigh and lower leg', 'kolano', 'She hurt her knee.', 'Uraziła kolano.', 33),
    ('calf', 'calf', 'noun', 'the back part of the lower leg', 'łydka', 'His calf cramped.', 'Złapał go skurcz łydki.', 34),
    ('ankle', 'ankle', 'noun', 'the joint between leg and foot', 'kostka', 'He twisted his ankle.', 'Skręcił kostkę.', 35),
    ('foot', 'foot', 'noun', 'the part you stand on', 'stopa', 'My foot is cold.', 'Moja stopa jest zimna.', 36),
    ('heel', 'heel', 'noun', 'the back part of the foot', 'pięta', 'Her heel hurts.', 'Boli ją pięta.', 37),
    ('toe', 'toe', 'noun', 'a digit on the foot', 'palec u stopy', 'He stubbed his toe.', 'Uderzył palcem u stopy.', 38),
    ('toenail', 'toenail', 'noun', 'the hard covering of a toe', 'paznokieć u stopy', 'He cut his toenail.', 'Obciął paznokieć u stopy.', 39),
    ('skin', 'skin', 'noun', 'the outer layer of the body', 'skóra', 'My skin is dry.', 'Moja skóra jest sucha.', 40),
    ('complexion', 'complexion', 'noun', 'the natural color of the skin', 'cera', 'Her complexion is clear.', 'Jej cera jest czysta.', 41),
    ('scar', 'scar', 'noun', 'a mark left after a wound', 'blizna', 'He has a small scar.', 'Ma małą bliznę.', 42),
    ('bruise', 'bruise', 'noun', 'a dark mark after a hit', 'siniak', 'The bruise is blue.', 'Siniak jest niebieski.', 43),
    ('cut', 'cut', 'noun', 'a small wound made by something sharp', 'skaleczenie', 'The cut is shallow.', 'Skaleczenie jest płytkie.', 44),
    ('scratch', 'scratch', 'noun', 'a thin mark on the skin', 'zadrapanie', 'The scratch is small.', 'Zadrapanie jest małe.', 45),
    ('rash', 'rash', 'noun', 'an area of irritated skin', 'wysypka', 'He has a rash on his arm.', 'Ma wysypkę na ramieniu.', 46),
    ('spot', 'spot', 'noun', 'a small mark on the skin', 'plamka', 'There is a spot on her cheek.', 'Na jej policzku jest plamka.', 47),
    ('pimple', 'pimple', 'noun', 'a small inflamed spot on the skin', 'pryszcz', 'A pimple appeared overnight.', 'Pryszcz pojawił się w nocy.', 48),
    ('wrinkle', 'wrinkle', 'noun', 'a small line on the skin', 'zmarszczka', 'Wrinkles appear with age.', 'Zmarszczki pojawiają się z wiekiem.', 49),
    ('freckle', 'freckle', 'noun', 'a small light-brown spot', 'pieg', 'She has freckles on her nose.', 'Ma piegi na nosie.', 50),
    ('mole', 'mole', 'noun', 'a small dark spot on the skin', 'pieprzyk', 'The mole is harmless.', 'Pieprzyk jest niegroźny.', 51),
    ('sweat', 'sweat', 'noun', 'the liquid from the skin when hot', 'pot', 'Sweat dripped from his face.', 'Pot kapał z jego twarzy.', 52),
    ('dirt', 'dirt', 'noun', 'soil or dust on the skin', 'brud', 'There is dirt on your hands.', 'Masz brud na rękach.', 53),
    ('brain', 'brain', 'noun', 'the organ that controls the body', 'mózg', 'The brain needs rest.', 'Mózg potrzebuje odpoczynku.', 54),
    ('throat', 'throat', 'noun', 'the passage in the neck', 'gardło', 'My throat is sore.', 'Boli mnie gardło.', 55),
    ('heart', 'heart', 'noun', 'the organ that pumps blood', 'serce', 'Her heart beats fast.', 'Jej serce bije szybko.', 56),
    ('lungs', 'lungs', 'noun', 'the organs used for breathing', 'płuca', 'The lungs need fresh air.', 'Płuca potrzebują świeżego powietrza.', 57),
    ('stomach', 'stomach', 'noun', 'the organ that digests food', 'żołądek', 'My stomach hurts.', 'Boli mnie żołądek.', 58),
    ('liver', 'liver', 'noun', 'the organ that processes nutrients', 'wątroba', 'The liver is important for health.', 'Wątroba jest ważna dla zdrowia.', 59),
    ('kidneys', 'kidneys', 'noun', 'the organs that filter blood', 'nerki', 'The kidneys work all the time.', 'Nerki pracują cały czas.', 60),
    ('intestines', 'intestines', 'noun', 'the long tubes in the belly', 'jelita', 'The intestines digest food.', 'Jelita trawią jedzenie.', 61),
    ('bladder', 'bladder', 'noun', 'the organ that stores urine', 'pęcherz', 'The bladder is full.', 'Pęcherz jest pełny.', 62),
    ('blood', 'blood', 'noun', 'the red liquid in the body', 'krew', 'Blood carries oxygen.', 'Krew przenosi tlen.', 63),
    ('muscles', 'muscles', 'noun', 'tissues that make movement possible', 'mięśnie', 'Strong muscles help posture.', 'Silne mięśnie pomagają w postawie.', 64),
    ('bones', 'bones', 'noun', 'the hard framework of the body', 'kości', 'Bones protect the organs.', 'Kości chronią narządy.', 65),
    ('scalp', 'scalp', 'noun', 'the skin covering the head', 'skóra głowy', 'The scalp is sensitive.', 'Skóra głowy jest wrażliwa.', 66),
    ('temple', 'temple', 'noun', 'the side of the head near the eyes', 'skroń', 'He touched his temple.', 'Dotknął swojej skroni.', 67),
    ('eyebrow', 'eyebrow', 'noun', 'the line of hair above the eye', 'brew', 'Her eyebrow is arched.', 'Jej brew jest wygięta.', 68),
    ('eyelid', 'eyelid', 'noun', 'the skin that covers the eye', 'powieka', 'She closed her eyelid.', 'Zamknęła powiekę.', 69),
    ('eyelash', 'eyelash', 'noun', 'a hair on the edge of the eyelid', 'rzęsa', 'An eyelash fell into my eye.', 'Rzęsa wpadła mi do oka.', 70),
    ('jaw', 'jaw', 'noun', 'the lower part of the face for chewing', 'szczęka', 'He clenched his jaw.', 'Zacisnął szczękę.', 71),
    ('cheekbone', 'cheekbone', 'noun', 'the bone of the cheek', 'kość policzkowa', 'Her cheekbones are high.', 'Ma wysokie kości policzkowe.', 72),
    ('beard', 'beard', 'noun', 'hair growing on the chin', 'broda', 'He grew a beard.', 'Zapuścił brodę.', 73),
    ('moustache', 'moustache', 'noun', 'hair above the upper lip', 'wąsy', 'His moustache is neat.', 'Jego wąsy są zadbane.', 74),
    ('upper lip', 'upper lip', 'noun', 'the top lip of the mouth', 'górna warga', 'The upper lip is swollen.', 'Górna warga jest spuchnięta.', 75),
    ('lower lip', 'lower lip', 'noun', 'the bottom lip of the mouth', 'dolna warga', 'She bit her lower lip.', 'Przygryzła dolną wargę.', 76),
    ('rib', 'rib', 'noun', 'a bone that protects the chest', 'żebro', 'He bruised a rib.', 'Stłukł sobie żebro.', 77),
    ('ribcage', 'ribcage', 'noun', 'the set of ribs around the chest', 'klatka żebrowa', 'The ribcage protects the heart.', 'Klatka żebrowa chroni serce.', 78),
    ('spine', 'spine', 'noun', 'the backbone', 'kręgosłup', 'Keep your spine straight.', 'Trzymaj kręgosłup prosto.', 79),
    ('shoulder blade', 'shoulder blade', 'noun', 'the bone on the back of the shoulder', 'łopatka', 'He felt pain near his shoulder blade.', 'Poczuł ból w okolicy łopatki.', 80),
    ('collarbone', 'collarbone', 'noun', 'the bone between the shoulder and chest', 'obojczyk', 'She broke her collarbone.', 'Złamała obojczyk.', 81),
    ('abdomen', 'abdomen', 'noun', 'the belly area of the body', 'brzuch', 'The abdomen is tense.', 'Brzuch jest napięty.', 82),
    ('navel', 'navel', 'noun', 'the belly button', 'pępek', 'The baby has a navel.', 'Dziecko ma pępek.', 83),
    ('pelvis', 'pelvis', 'noun', 'the bony structure of the hips', 'miednica', 'The pelvis supports the spine.', 'Miednica podtrzymuje kręgosłup.', 84),
    ('forearm', 'forearm', 'noun', 'the part of the arm below the elbow', 'przedramię', 'He has a tattoo on his forearm.', 'Ma tatuaż na przedramieniu.', 85),
    ('upper arm', 'upper arm', 'noun', 'the part of the arm above the elbow', 'ramię', 'She stretched her upper arm.', 'Rozciągnęła ramię.', 86),
    ('palm', 'palm', 'noun', 'the inside of the hand', 'dłoń', 'He held it in his palm.', 'Trzymał to w dłoni.', 87),
    ('knuckle', 'knuckle', 'noun', 'the joint of a finger', 'knykieć', 'His knuckles are bruised.', 'Jego knykcie są posiniaczone.', 88),
    ('fingertip', 'fingertip', 'noun', 'the tip of a finger', 'opuszek palca', 'Use your fingertip.', 'Użyj opuszka palca.', 89),
    ('armpit', 'armpit', 'noun', 'the area under the shoulder', 'pacha', 'He has a rash in his armpit.', 'Ma wysypkę pod pachą.', 90),
    ('thumb', 'thumb', 'noun', 'the short thick finger', 'kciuk', 'He hurt his thumb.', 'Uraził kciuk.', 91),
    ('kneecap', 'kneecap', 'noun', 'the bone at the front of the knee', 'rzepka', 'She hit her kneecap.', 'Uderzyła rzepkę.', 92),
    ('shin', 'shin', 'noun', 'the front of the lower leg', 'goleń', 'He has a cut on his shin.', 'Ma skaleczenie na goleni.', 93),
    ('Achilles tendon', 'achilles tendon', 'noun', 'the tendon at the back of the ankle', 'ścięgno Achillesa', 'He injured his Achilles tendon.', 'Uszkodził ścięgno Achillesa.', 94),
    ('instep', 'instep', 'noun', 'the top of the foot', 'podbicie stopy', 'The instep is swollen.', 'Podbicie stopy jest spuchnięte.', 95),
    ('sole', 'sole', 'noun', 'the underside of the foot', 'podeszwa', 'The sole of my foot hurts.', 'Boli mnie podeszwa stopy.', 96),
    ('ball of the foot', 'ball of the foot', 'noun', 'the padded area under the toes', 'poduszka stopy', 'She stood on the ball of her foot.', 'Stanęła na poduszce stopy.', 97),
    ('big toe', 'big toe', 'noun', 'the largest toe', 'duży palec u stopy', 'He broke his big toe.', 'Złamał duży palec u stopy.', 98),
    ('little toe', 'little toe', 'noun', 'the smallest toe', 'mały palec u stopy', 'The little toe is bruised.', 'Mały palec u stopy jest posiniaczony.', 99),
    ('blemish', 'blemish', 'noun', 'a small mark on the skin', 'niedoskonałość', 'This blemish will fade.', 'Ta niedoskonałość zniknie.', 100),
    ('scar tissue', 'scar tissue', 'noun', 'tissue that forms after a wound', 'tkanka bliznowata', 'Scar tissue is stiff.', 'Tkanka bliznowata jest sztywna.', 101),
    ('burn', 'burn', 'noun', 'a wound caused by heat', 'oparzenie', 'The burn is painful.', 'Oparzenie jest bolesne.', 102),
    ('blister', 'blister', 'noun', 'a small bubble on the skin', 'pęcherz', 'A blister formed on his heel.', 'Na pięcie zrobił się pęcherz.', 103),
    ('swelling', 'swelling', 'noun', 'an enlarged area from injury', 'obrzęk', 'The swelling went down.', 'Obrzęk ustąpił.', 104),
    ('irritation', 'irritation', 'noun', 'a red or itchy reaction', 'podrażnienie', 'The cream reduced irritation.', 'Krem zmniejszył podrażnienie.', 105),
    ('redness', 'redness', 'noun', 'red color on the skin', 'zaczerwienienie', 'Redness appeared around the cut.', 'Wokół skaleczenia pojawiło się zaczerwienienie.', 106),
    ('stretch marks', 'stretch marks', 'noun', 'lines on the skin after stretching', 'rozstępy', 'Stretch marks can fade over time.', 'Rozstępy mogą z czasem zblednąć.', 107),
    ('flaky skin', 'flaky skin', 'noun', 'skin that peels in small pieces', 'łuszcząca się skóra', 'Flaky skin needs moisture.', 'Łuszcząca się skóra potrzebuje nawilżenia.', 108),
    ('spinal cord', 'spinal cord', 'noun', 'the nerve cord inside the spine', 'rdzeń kręgowy', 'The spinal cord sends signals.', 'Rdzeń kręgowy wysyła sygnały.', 109),
    ('ribs', 'ribs', 'noun', 'the bones around the chest', 'żebra', 'He felt pain in his ribs.', 'Czuł ból w żebrach.', 110),
    ('pancreas', 'pancreas', 'noun', 'the organ that produces insulin', 'trzustka', 'The pancreas helps digestion.', 'Trzustka wspiera trawienie.', 111),
    ('spleen', 'spleen', 'noun', 'the organ near the stomach', 'śledziona', 'The spleen filters blood.', 'Śledziona filtruje krew.', 112),
    ('gallbladder', 'gallbladder', 'noun', 'the organ that stores bile', 'pęcherzyk żółciowy', 'The gallbladder stores bile.', 'Pęcherzyk żółciowy magazynuje żółć.', 113),
    ('esophagus', 'esophagus', 'noun', 'the tube from mouth to stomach', 'przełyk', 'Food passes through the esophagus.', 'Jedzenie przechodzi przez przełyk.', 114),
    ('colon', 'colon', 'noun', 'the large intestine', 'okrężnica', 'The colon absorbs water.', 'Okrężnica wchłania wodę.', 115),
    ('small intestine', 'small intestine', 'noun', 'the long, thin intestine', 'jelito cienkie', 'The small intestine absorbs nutrients.', 'Jelito cienkie wchłania składniki odżywcze.', 116),
    ('large intestine', 'large intestine', 'noun', 'the wider part of the intestine', 'jelito grube', 'The large intestine absorbs water.', 'Jelito grube wchłania wodę.', 117),
    ('appendix', 'appendix', 'noun', 'a small pouch near the intestines', 'wyrostek robaczkowy', 'The appendix can get inflamed.', 'Wyrostek robaczkowy może się zapalić.', 118),
    ('diaphragm', 'diaphragm', 'noun', 'the muscle used for breathing', 'przepona', 'The diaphragm moves when you breathe.', 'Przepona porusza się podczas oddychania.', 119),
    ('veins', 'veins', 'noun', 'blood vessels that carry blood to the heart', 'żyły', 'Veins carry blood back.', 'Żyły odprowadzają krew.', 120),
    ('arteries', 'arteries', 'noun', 'blood vessels that carry blood from the heart', 'tętnice', 'Arteries carry blood out.', 'Tętnice odprowadzają krew z serca.', 121)
)
insert into lexicon_entries (lemma, lemma_norm, pos)
select w.lemma, w.lemma_norm, w.pos
from words w
where not exists (
  select 1 from lexicon_entries e
  where e.lemma_norm = w.lemma_norm and e.pos = w.pos
);

with words(lemma, lemma_norm, pos, definition_en, translation_pl, example_en, example_pl, order_index) as (
  values
    ('head', 'head', 'noun', 'the upper part of the body', 'głowa', 'My head hurts today.', 'Dziś boli mnie głowa.', 1),
    ('face', 'face', 'noun', 'the front part of the head', 'twarz', 'Her face looks tired.', 'Jej twarz wygląda na zmęczoną.', 2),
    ('hair', 'hair', 'noun', 'the strands growing on the head', 'włosy', 'His hair is wet.', 'Jego włosy są mokre.', 3),
    ('forehead', 'forehead', 'noun', 'the part above the eyes', 'czoło', 'She touched her forehead.', 'Dotknęła swojego czoła.', 4),
    ('eye', 'eye', 'noun', 'the organ of sight', 'oko', 'My eye is red.', 'Moje oko jest czerwone.', 5),
    ('ear', 'ear', 'noun', 'the organ of hearing', 'ucho', 'He has an earache.', 'Ma ból ucha.', 6),
    ('nose', 'nose', 'noun', 'the organ used for breathing and smelling', 'nos', 'My nose is cold.', 'Mój nos jest zimny.', 7),
    ('mouth', 'mouth', 'noun', 'the opening used to eat and speak', 'usta', 'Open your mouth, please.', 'Otwórz usta, proszę.', 8),
    ('lip', 'lip', 'noun', 'the edge of the mouth', 'warga', 'She bit her lip.', 'Przygryzła wargę.', 9),
    ('cheek', 'cheek', 'noun', 'the side of the face', 'policzek', 'He kissed her cheek.', 'Pocałował ją w policzek.', 10),
    ('tooth', 'tooth', 'noun', 'a hard structure in the mouth', 'ząb', 'This tooth hurts.', 'Ten ząb boli.', 11),
    ('tongue', 'tongue', 'noun', 'the muscle in the mouth', 'język', 'He burned his tongue.', 'Oparzył sobie język.', 12),
    ('chin', 'chin', 'noun', 'the lower part of the face', 'broda', 'He has a strong chin.', 'Ma mocną brodę.', 13),
    ('facial hair', 'facial hair', 'noun', 'hair growing on the face', 'zarost', 'Facial hair grows fast.', 'Zarost rośnie szybko.', 14),
    ('torso', 'torso', 'noun', 'the main part of the body without limbs', 'tułów', 'The torso is strong.', 'Tułów jest silny.', 15),
    ('chest', 'chest', 'noun', 'the front of the upper body', 'klatka piersiowa', 'He felt pain in his chest.', 'Poczuł ból w klatce piersiowej.', 16),
    ('back', 'back', 'noun', 'the rear part of the body', 'plecy', 'My back is sore.', 'Bolą mnie plecy.', 17),
    ('neck', 'neck', 'noun', 'the part connecting head and body', 'szyja', 'She wears a scarf on her neck.', 'Nosi szalik na szyi.', 18),
    ('belly', 'belly', 'noun', 'the front of the body between chest and hips', 'brzuch', 'My belly feels full.', 'Mój brzuch jest pełny.', 19),
    ('waist', 'waist', 'noun', 'the narrow middle part of the body', 'talia', 'The belt sits on the waist.', 'Pasek leży na talii.', 20),
    ('hip', 'hip', 'noun', 'the side of the body above the leg', 'biodro', 'She hurt her hip.', 'Uraziła sobie biodro.', 21),
    ('shoulder', 'shoulder', 'noun', 'the joint connecting arm to body', 'bark', 'He carried the bag on his shoulder.', 'Niósł torbę na barku.', 22),
    ('arm', 'arm', 'noun', 'the upper limb from shoulder to hand', 'ramię', 'He raised his arm.', 'Podniósł ramię.', 23),
    ('elbow', 'elbow', 'noun', 'the joint in the middle of the arm', 'łokieć', 'She leaned on her elbow.', 'Oparła się na łokciu.', 24),
    ('wrist', 'wrist', 'noun', 'the joint between hand and arm', 'nadgarstek', 'He wears a watch on his wrist.', 'Nosi zegarek na nadgarstku.', 25),
    ('hand', 'hand', 'noun', 'the part at the end of the arm', 'dłoń', 'Wash your hands.', 'Umyj dłonie.', 26),
    ('finger', 'finger', 'noun', 'a digit on the hand', 'palec', 'He cut his finger.', 'Skaleczył palec.', 27),
    ('nail', 'nail', 'noun', 'the hard covering at the end of a finger', 'paznokieć', 'She painted her nails.', 'Pomalowała paznokcie.', 28),
    ('nipple', 'nipple', 'noun', 'the small part in the center of the breast', 'sutek', 'The baby touched the nipple.', 'Dziecko dotknęło sutka.', 29),
    ('breast', 'breast', 'noun', 'the part on the front of the chest', 'pierś', 'She felt pain in her breast.', 'Poczuła ból w piersi.', 30),
    ('leg', 'leg', 'noun', 'the limb used for walking', 'noga', 'My leg is tired.', 'Moja noga jest zmęczona.', 31),
    ('thigh', 'thigh', 'noun', 'the upper part of the leg', 'udo', 'He has strong thighs.', 'Ma mocne uda.', 32),
    ('knee', 'knee', 'noun', 'the joint between thigh and lower leg', 'kolano', 'She hurt her knee.', 'Uraziła kolano.', 33),
    ('calf', 'calf', 'noun', 'the back part of the lower leg', 'łydka', 'His calf cramped.', 'Złapał go skurcz łydki.', 34),
    ('ankle', 'ankle', 'noun', 'the joint between leg and foot', 'kostka', 'He twisted his ankle.', 'Skręcił kostkę.', 35),
    ('foot', 'foot', 'noun', 'the part you stand on', 'stopa', 'My foot is cold.', 'Moja stopa jest zimna.', 36),
    ('heel', 'heel', 'noun', 'the back part of the foot', 'pięta', 'Her heel hurts.', 'Boli ją pięta.', 37),
    ('toe', 'toe', 'noun', 'a digit on the foot', 'palec u stopy', 'He stubbed his toe.', 'Uderzył palcem u stopy.', 38),
    ('toenail', 'toenail', 'noun', 'the hard covering of a toe', 'paznokieć u stopy', 'He cut his toenail.', 'Obciął paznokieć u stopy.', 39),
    ('skin', 'skin', 'noun', 'the outer layer of the body', 'skóra', 'My skin is dry.', 'Moja skóra jest sucha.', 40),
    ('complexion', 'complexion', 'noun', 'the natural color of the skin', 'cera', 'Her complexion is clear.', 'Jej cera jest czysta.', 41),
    ('scar', 'scar', 'noun', 'a mark left after a wound', 'blizna', 'He has a small scar.', 'Ma małą bliznę.', 42),
    ('bruise', 'bruise', 'noun', 'a dark mark after a hit', 'siniak', 'The bruise is blue.', 'Siniak jest niebieski.', 43),
    ('cut', 'cut', 'noun', 'a small wound made by something sharp', 'skaleczenie', 'The cut is shallow.', 'Skaleczenie jest płytkie.', 44),
    ('scratch', 'scratch', 'noun', 'a thin mark on the skin', 'zadrapanie', 'The scratch is small.', 'Zadrapanie jest małe.', 45),
    ('rash', 'rash', 'noun', 'an area of irritated skin', 'wysypka', 'He has a rash on his arm.', 'Ma wysypkę na ramieniu.', 46),
    ('spot', 'spot', 'noun', 'a small mark on the skin', 'plamka', 'There is a spot on her cheek.', 'Na jej policzku jest plamka.', 47),
    ('pimple', 'pimple', 'noun', 'a small inflamed spot on the skin', 'pryszcz', 'A pimple appeared overnight.', 'Pryszcz pojawił się w nocy.', 48),
    ('wrinkle', 'wrinkle', 'noun', 'a small line on the skin', 'zmarszczka', 'Wrinkles appear with age.', 'Zmarszczki pojawiają się z wiekiem.', 49),
    ('freckle', 'freckle', 'noun', 'a small light-brown spot', 'pieg', 'She has freckles on her nose.', 'Ma piegi na nosie.', 50),
    ('mole', 'mole', 'noun', 'a small dark spot on the skin', 'pieprzyk', 'The mole is harmless.', 'Pieprzyk jest niegroźny.', 51),
    ('sweat', 'sweat', 'noun', 'the liquid from the skin when hot', 'pot', 'Sweat dripped from his face.', 'Pot kapał z jego twarzy.', 52),
    ('dirt', 'dirt', 'noun', 'soil or dust on the skin', 'brud', 'There is dirt on your hands.', 'Masz brud na rękach.', 53),
    ('brain', 'brain', 'noun', 'the organ that controls the body', 'mózg', 'The brain needs rest.', 'Mózg potrzebuje odpoczynku.', 54),
    ('throat', 'throat', 'noun', 'the passage in the neck', 'gardło', 'My throat is sore.', 'Boli mnie gardło.', 55),
    ('heart', 'heart', 'noun', 'the organ that pumps blood', 'serce', 'Her heart beats fast.', 'Jej serce bije szybko.', 56),
    ('lungs', 'lungs', 'noun', 'the organs used for breathing', 'płuca', 'The lungs need fresh air.', 'Płuca potrzebują świeżego powietrza.', 57),
    ('stomach', 'stomach', 'noun', 'the organ that digests food', 'żołądek', 'My stomach hurts.', 'Boli mnie żołądek.', 58),
    ('liver', 'liver', 'noun', 'the organ that processes nutrients', 'wątroba', 'The liver is important for health.', 'Wątroba jest ważna dla zdrowia.', 59),
    ('kidneys', 'kidneys', 'noun', 'the organs that filter blood', 'nerki', 'The kidneys work all the time.', 'Nerki pracują cały czas.', 60),
    ('intestines', 'intestines', 'noun', 'the long tubes in the belly', 'jelita', 'The intestines digest food.', 'Jelita trawią jedzenie.', 61),
    ('bladder', 'bladder', 'noun', 'the organ that stores urine', 'pęcherz', 'The bladder is full.', 'Pęcherz jest pełny.', 62),
    ('blood', 'blood', 'noun', 'the red liquid in the body', 'krew', 'Blood carries oxygen.', 'Krew przenosi tlen.', 63),
    ('muscles', 'muscles', 'noun', 'tissues that make movement possible', 'mięśnie', 'Strong muscles help posture.', 'Silne mięśnie pomagają w postawie.', 64),
    ('bones', 'bones', 'noun', 'the hard framework of the body', 'kości', 'Bones protect the organs.', 'Kości chronią narządy.', 65),
    ('scalp', 'scalp', 'noun', 'the skin covering the head', 'skóra głowy', 'The scalp is sensitive.', 'Skóra głowy jest wrażliwa.', 66),
    ('temple', 'temple', 'noun', 'the side of the head near the eyes', 'skroń', 'He touched his temple.', 'Dotknął swojej skroni.', 67),
    ('eyebrow', 'eyebrow', 'noun', 'the line of hair above the eye', 'brew', 'Her eyebrow is arched.', 'Jej brew jest wygięta.', 68),
    ('eyelid', 'eyelid', 'noun', 'the skin that covers the eye', 'powieka', 'She closed her eyelid.', 'Zamknęła powiekę.', 69),
    ('eyelash', 'eyelash', 'noun', 'a hair on the edge of the eyelid', 'rzęsa', 'An eyelash fell into my eye.', 'Rzęsa wpadła mi do oka.', 70),
    ('jaw', 'jaw', 'noun', 'the lower part of the face for chewing', 'szczęka', 'He clenched his jaw.', 'Zacisnął szczękę.', 71),
    ('cheekbone', 'cheekbone', 'noun', 'the bone of the cheek', 'kość policzkowa', 'Her cheekbones are high.', 'Ma wysokie kości policzkowe.', 72),
    ('beard', 'beard', 'noun', 'hair growing on the chin', 'broda', 'He grew a beard.', 'Zapuścił brodę.', 73),
    ('moustache', 'moustache', 'noun', 'hair above the upper lip', 'wąsy', 'His moustache is neat.', 'Jego wąsy są zadbane.', 74),
    ('upper lip', 'upper lip', 'noun', 'the top lip of the mouth', 'górna warga', 'The upper lip is swollen.', 'Górna warga jest spuchnięta.', 75),
    ('lower lip', 'lower lip', 'noun', 'the bottom lip of the mouth', 'dolna warga', 'She bit her lower lip.', 'Przygryzła dolną wargę.', 76),
    ('rib', 'rib', 'noun', 'a bone that protects the chest', 'żebro', 'He bruised a rib.', 'Stłukł sobie żebro.', 77),
    ('ribcage', 'ribcage', 'noun', 'the set of ribs around the chest', 'klatka żebrowa', 'The ribcage protects the heart.', 'Klatka żebrowa chroni serce.', 78),
    ('spine', 'spine', 'noun', 'the backbone', 'kręgosłup', 'Keep your spine straight.', 'Trzymaj kręgosłup prosto.', 79),
    ('shoulder blade', 'shoulder blade', 'noun', 'the bone on the back of the shoulder', 'łopatka', 'He felt pain near his shoulder blade.', 'Poczuł ból w okolicy łopatki.', 80),
    ('collarbone', 'collarbone', 'noun', 'the bone between the shoulder and chest', 'obojczyk', 'She broke her collarbone.', 'Złamała obojczyk.', 81),
    ('abdomen', 'abdomen', 'noun', 'the belly area of the body', 'brzuch', 'The abdomen is tense.', 'Brzuch jest napięty.', 82),
    ('navel', 'navel', 'noun', 'the belly button', 'pępek', 'The baby has a navel.', 'Dziecko ma pępek.', 83),
    ('pelvis', 'pelvis', 'noun', 'the bony structure of the hips', 'miednica', 'The pelvis supports the spine.', 'Miednica podtrzymuje kręgosłup.', 84),
    ('forearm', 'forearm', 'noun', 'the part of the arm below the elbow', 'przedramię', 'He has a tattoo on his forearm.', 'Ma tatuaż na przedramieniu.', 85),
    ('upper arm', 'upper arm', 'noun', 'the part of the arm above the elbow', 'ramię', 'She stretched her upper arm.', 'Rozciągnęła ramię.', 86),
    ('palm', 'palm', 'noun', 'the inside of the hand', 'dłoń', 'He held it in his palm.', 'Trzymał to w dłoni.', 87),
    ('knuckle', 'knuckle', 'noun', 'the joint of a finger', 'knykieć', 'His knuckles are bruised.', 'Jego knykcie są posiniaczone.', 88),
    ('fingertip', 'fingertip', 'noun', 'the tip of a finger', 'opuszek palca', 'Use your fingertip.', 'Użyj opuszka palca.', 89),
    ('armpit', 'armpit', 'noun', 'the area under the shoulder', 'pacha', 'He has a rash in his armpit.', 'Ma wysypkę pod pachą.', 90),
    ('thumb', 'thumb', 'noun', 'the short thick finger', 'kciuk', 'He hurt his thumb.', 'Uraził kciuk.', 91),
    ('kneecap', 'kneecap', 'noun', 'the bone at the front of the knee', 'rzepka', 'She hit her kneecap.', 'Uderzyła rzepkę.', 92),
    ('shin', 'shin', 'noun', 'the front of the lower leg', 'goleń', 'He has a cut on his shin.', 'Ma skaleczenie na goleni.', 93),
    ('Achilles tendon', 'achilles tendon', 'noun', 'the tendon at the back of the ankle', 'ścięgno Achillesa', 'He injured his Achilles tendon.', 'Uszkodził ścięgno Achillesa.', 94),
    ('instep', 'instep', 'noun', 'the top of the foot', 'podbicie stopy', 'The instep is swollen.', 'Podbicie stopy jest spuchnięte.', 95),
    ('sole', 'sole', 'noun', 'the underside of the foot', 'podeszwa', 'The sole of my foot hurts.', 'Boli mnie podeszwa stopy.', 96),
    ('ball of the foot', 'ball of the foot', 'noun', 'the padded area under the toes', 'poduszka stopy', 'She stood on the ball of her foot.', 'Stanęła na poduszce stopy.', 97),
    ('big toe', 'big toe', 'noun', 'the largest toe', 'duży palec u stopy', 'He broke his big toe.', 'Złamał duży palec u stopy.', 98),
    ('little toe', 'little toe', 'noun', 'the smallest toe', 'mały palec u stopy', 'The little toe is bruised.', 'Mały palec u stopy jest posiniaczony.', 99),
    ('blemish', 'blemish', 'noun', 'a small mark on the skin', 'niedoskonałość', 'This blemish will fade.', 'Ta niedoskonałość zniknie.', 100),
    ('scar tissue', 'scar tissue', 'noun', 'tissue that forms after a wound', 'tkanka bliznowata', 'Scar tissue is stiff.', 'Tkanka bliznowata jest sztywna.', 101),
    ('burn', 'burn', 'noun', 'a wound caused by heat', 'oparzenie', 'The burn is painful.', 'Oparzenie jest bolesne.', 102),
    ('blister', 'blister', 'noun', 'a small bubble on the skin', 'pęcherz', 'A blister formed on his heel.', 'Na pięcie zrobił się pęcherz.', 103),
    ('swelling', 'swelling', 'noun', 'an enlarged area from injury', 'obrzęk', 'The swelling went down.', 'Obrzęk ustąpił.', 104),
    ('irritation', 'irritation', 'noun', 'a red or itchy reaction', 'podrażnienie', 'The cream reduced irritation.', 'Krem zmniejszył podrażnienie.', 105),
    ('redness', 'redness', 'noun', 'red color on the skin', 'zaczerwienienie', 'Redness appeared around the cut.', 'Wokół skaleczenia pojawiło się zaczerwienienie.', 106),
    ('stretch marks', 'stretch marks', 'noun', 'lines on the skin after stretching', 'rozstępy', 'Stretch marks can fade over time.', 'Rozstępy mogą z czasem zblednąć.', 107),
    ('flaky skin', 'flaky skin', 'noun', 'skin that peels in small pieces', 'łuszcząca się skóra', 'Flaky skin needs moisture.', 'Łuszcząca się skóra potrzebuje nawilżenia.', 108),
    ('spinal cord', 'spinal cord', 'noun', 'the nerve cord inside the spine', 'rdzeń kręgowy', 'The spinal cord sends signals.', 'Rdzeń kręgowy wysyła sygnały.', 109),
    ('ribs', 'ribs', 'noun', 'the bones around the chest', 'żebra', 'He felt pain in his ribs.', 'Czuł ból w żebrach.', 110),
    ('pancreas', 'pancreas', 'noun', 'the organ that produces insulin', 'trzustka', 'The pancreas helps digestion.', 'Trzustka wspiera trawienie.', 111),
    ('spleen', 'spleen', 'noun', 'the organ near the stomach', 'śledziona', 'The spleen filters blood.', 'Śledziona filtruje krew.', 112),
    ('gallbladder', 'gallbladder', 'noun', 'the organ that stores bile', 'pęcherzyk żółciowy', 'The gallbladder stores bile.', 'Pęcherzyk żółciowy magazynuje żółć.', 113),
    ('esophagus', 'esophagus', 'noun', 'the tube from mouth to stomach', 'przełyk', 'Food passes through the esophagus.', 'Jedzenie przechodzi przez przełyk.', 114),
    ('colon', 'colon', 'noun', 'the large intestine', 'okrężnica', 'The colon absorbs water.', 'Okrężnica wchłania wodę.', 115),
    ('small intestine', 'small intestine', 'noun', 'the long, thin intestine', 'jelito cienkie', 'The small intestine absorbs nutrients.', 'Jelito cienkie wchłania składniki odżywcze.', 116),
    ('large intestine', 'large intestine', 'noun', 'the wider part of the intestine', 'jelito grube', 'The large intestine absorbs water.', 'Jelito grube wchłania wodę.', 117),
    ('appendix', 'appendix', 'noun', 'a small pouch near the intestines', 'wyrostek robaczkowy', 'The appendix can get inflamed.', 'Wyrostek robaczkowy może się zapalić.', 118),
    ('diaphragm', 'diaphragm', 'noun', 'the muscle used for breathing', 'przepona', 'The diaphragm moves when you breathe.', 'Przepona porusza się podczas oddychania.', 119),
    ('veins', 'veins', 'noun', 'blood vessels that carry blood to the heart', 'żyły', 'Veins carry blood back.', 'Żyły odprowadzają krew.', 120),
    ('arteries', 'arteries', 'noun', 'blood vessels that carry blood from the heart', 'tętnice', 'Arteries carry blood out.', 'Tętnice odprowadzają krew z serca.', 121)
)
insert into lexicon_senses (entry_id, definition_en, domain, sense_order)
select e.id, w.definition_en, 'body', 0
from words w
join lexicon_entries e on e.lemma_norm = w.lemma_norm and e.pos = w.pos
where not exists (
  select 1 from lexicon_senses s
  where s.entry_id = e.id and s.sense_order = 0
);

with words(lemma, lemma_norm, pos, definition_en, translation_pl, example_en, example_pl, order_index) as (
  values
    ('head', 'head', 'noun', 'the upper part of the body', 'głowa', 'My head hurts today.', 'Dziś boli mnie głowa.', 1),
    ('face', 'face', 'noun', 'the front part of the head', 'twarz', 'Her face looks tired.', 'Jej twarz wygląda na zmęczoną.', 2),
    ('hair', 'hair', 'noun', 'the strands growing on the head', 'włosy', 'His hair is wet.', 'Jego włosy są mokre.', 3),
    ('forehead', 'forehead', 'noun', 'the part above the eyes', 'czoło', 'She touched her forehead.', 'Dotknęła swojego czoła.', 4),
    ('eye', 'eye', 'noun', 'the organ of sight', 'oko', 'My eye is red.', 'Moje oko jest czerwone.', 5),
    ('ear', 'ear', 'noun', 'the organ of hearing', 'ucho', 'He has an earache.', 'Ma ból ucha.', 6),
    ('nose', 'nose', 'noun', 'the organ used for breathing and smelling', 'nos', 'My nose is cold.', 'Mój nos jest zimny.', 7),
    ('mouth', 'mouth', 'noun', 'the opening used to eat and speak', 'usta', 'Open your mouth, please.', 'Otwórz usta, proszę.', 8),
    ('lip', 'lip', 'noun', 'the edge of the mouth', 'warga', 'She bit her lip.', 'Przygryzła wargę.', 9),
    ('cheek', 'cheek', 'noun', 'the side of the face', 'policzek', 'He kissed her cheek.', 'Pocałował ją w policzek.', 10),
    ('tooth', 'tooth', 'noun', 'a hard structure in the mouth', 'ząb', 'This tooth hurts.', 'Ten ząb boli.', 11),
    ('tongue', 'tongue', 'noun', 'the muscle in the mouth', 'język', 'He burned his tongue.', 'Oparzył sobie język.', 12),
    ('chin', 'chin', 'noun', 'the lower part of the face', 'broda', 'He has a strong chin.', 'Ma mocną brodę.', 13),
    ('facial hair', 'facial hair', 'noun', 'hair growing on the face', 'zarost', 'Facial hair grows fast.', 'Zarost rośnie szybko.', 14),
    ('torso', 'torso', 'noun', 'the main part of the body without limbs', 'tułów', 'The torso is strong.', 'Tułów jest silny.', 15),
    ('chest', 'chest', 'noun', 'the front of the upper body', 'klatka piersiowa', 'He felt pain in his chest.', 'Poczuł ból w klatce piersiowej.', 16),
    ('back', 'back', 'noun', 'the rear part of the body', 'plecy', 'My back is sore.', 'Bolą mnie plecy.', 17),
    ('neck', 'neck', 'noun', 'the part connecting head and body', 'szyja', 'She wears a scarf on her neck.', 'Nosi szalik na szyi.', 18),
    ('belly', 'belly', 'noun', 'the front of the body between chest and hips', 'brzuch', 'My belly feels full.', 'Mój brzuch jest pełny.', 19),
    ('waist', 'waist', 'noun', 'the narrow middle part of the body', 'talia', 'The belt sits on the waist.', 'Pasek leży na talii.', 20),
    ('hip', 'hip', 'noun', 'the side of the body above the leg', 'biodro', 'She hurt her hip.', 'Uraziła sobie biodro.', 21),
    ('shoulder', 'shoulder', 'noun', 'the joint connecting arm to body', 'bark', 'He carried the bag on his shoulder.', 'Niósł torbę na barku.', 22),
    ('arm', 'arm', 'noun', 'the upper limb from shoulder to hand', 'ramię', 'He raised his arm.', 'Podniósł ramię.', 23),
    ('elbow', 'elbow', 'noun', 'the joint in the middle of the arm', 'łokieć', 'She leaned on her elbow.', 'Oparła się na łokciu.', 24),
    ('wrist', 'wrist', 'noun', 'the joint between hand and arm', 'nadgarstek', 'He wears a watch on his wrist.', 'Nosi zegarek na nadgarstku.', 25),
    ('hand', 'hand', 'noun', 'the part at the end of the arm', 'dłoń', 'Wash your hands.', 'Umyj dłonie.', 26),
    ('finger', 'finger', 'noun', 'a digit on the hand', 'palec', 'He cut his finger.', 'Skaleczył palec.', 27),
    ('nail', 'nail', 'noun', 'the hard covering at the end of a finger', 'paznokieć', 'She painted her nails.', 'Pomalowała paznokcie.', 28),
    ('nipple', 'nipple', 'noun', 'the small part in the center of the breast', 'sutek', 'The baby touched the nipple.', 'Dziecko dotknęło sutka.', 29),
    ('breast', 'breast', 'noun', 'the part on the front of the chest', 'pierś', 'She felt pain in her breast.', 'Poczuła ból w piersi.', 30),
    ('leg', 'leg', 'noun', 'the limb used for walking', 'noga', 'My leg is tired.', 'Moja noga jest zmęczona.', 31),
    ('thigh', 'thigh', 'noun', 'the upper part of the leg', 'udo', 'He has strong thighs.', 'Ma mocne uda.', 32),
    ('knee', 'knee', 'noun', 'the joint between thigh and lower leg', 'kolano', 'She hurt her knee.', 'Uraziła kolano.', 33),
    ('calf', 'calf', 'noun', 'the back part of the lower leg', 'łydka', 'His calf cramped.', 'Złapał go skurcz łydki.', 34),
    ('ankle', 'ankle', 'noun', 'the joint between leg and foot', 'kostka', 'He twisted his ankle.', 'Skręcił kostkę.', 35),
    ('foot', 'foot', 'noun', 'the part you stand on', 'stopa', 'My foot is cold.', 'Moja stopa jest zimna.', 36),
    ('heel', 'heel', 'noun', 'the back part of the foot', 'pięta', 'Her heel hurts.', 'Boli ją pięta.', 37),
    ('toe', 'toe', 'noun', 'a digit on the foot', 'palec u stopy', 'He stubbed his toe.', 'Uderzył palcem u stopy.', 38),
    ('toenail', 'toenail', 'noun', 'the hard covering of a toe', 'paznokieć u stopy', 'He cut his toenail.', 'Obciął paznokieć u stopy.', 39),
    ('skin', 'skin', 'noun', 'the outer layer of the body', 'skóra', 'My skin is dry.', 'Moja skóra jest sucha.', 40),
    ('complexion', 'complexion', 'noun', 'the natural color of the skin', 'cera', 'Her complexion is clear.', 'Jej cera jest czysta.', 41),
    ('scar', 'scar', 'noun', 'a mark left after a wound', 'blizna', 'He has a small scar.', 'Ma małą bliznę.', 42),
    ('bruise', 'bruise', 'noun', 'a dark mark after a hit', 'siniak', 'The bruise is blue.', 'Siniak jest niebieski.', 43),
    ('cut', 'cut', 'noun', 'a small wound made by something sharp', 'skaleczenie', 'The cut is shallow.', 'Skaleczenie jest płytkie.', 44),
    ('scratch', 'scratch', 'noun', 'a thin mark on the skin', 'zadrapanie', 'The scratch is small.', 'Zadrapanie jest małe.', 45),
    ('rash', 'rash', 'noun', 'an area of irritated skin', 'wysypka', 'He has a rash on his arm.', 'Ma wysypkę na ramieniu.', 46),
    ('spot', 'spot', 'noun', 'a small mark on the skin', 'plamka', 'There is a spot on her cheek.', 'Na jej policzku jest plamka.', 47),
    ('pimple', 'pimple', 'noun', 'a small inflamed spot on the skin', 'pryszcz', 'A pimple appeared overnight.', 'Pryszcz pojawił się w nocy.', 48),
    ('wrinkle', 'wrinkle', 'noun', 'a small line on the skin', 'zmarszczka', 'Wrinkles appear with age.', 'Zmarszczki pojawiają się z wiekiem.', 49),
    ('freckle', 'freckle', 'noun', 'a small light-brown spot', 'pieg', 'She has freckles on her nose.', 'Ma piegi na nosie.', 50),
    ('mole', 'mole', 'noun', 'a small dark spot on the skin', 'pieprzyk', 'The mole is harmless.', 'Pieprzyk jest niegroźny.', 51),
    ('sweat', 'sweat', 'noun', 'the liquid from the skin when hot', 'pot', 'Sweat dripped from his face.', 'Pot kapał z jego twarzy.', 52),
    ('dirt', 'dirt', 'noun', 'soil or dust on the skin', 'brud', 'There is dirt on your hands.', 'Masz brud na rękach.', 53),
    ('brain', 'brain', 'noun', 'the organ that controls the body', 'mózg', 'The brain needs rest.', 'Mózg potrzebuje odpoczynku.', 54),
    ('throat', 'throat', 'noun', 'the passage in the neck', 'gardło', 'My throat is sore.', 'Boli mnie gardło.', 55),
    ('heart', 'heart', 'noun', 'the organ that pumps blood', 'serce', 'Her heart beats fast.', 'Jej serce bije szybko.', 56),
    ('lungs', 'lungs', 'noun', 'the organs used for breathing', 'płuca', 'The lungs need fresh air.', 'Płuca potrzebują świeżego powietrza.', 57),
    ('stomach', 'stomach', 'noun', 'the organ that digests food', 'żołądek', 'My stomach hurts.', 'Boli mnie żołądek.', 58),
    ('liver', 'liver', 'noun', 'the organ that processes nutrients', 'wątroba', 'The liver is important for health.', 'Wątroba jest ważna dla zdrowia.', 59),
    ('kidneys', 'kidneys', 'noun', 'the organs that filter blood', 'nerki', 'The kidneys work all the time.', 'Nerki pracują cały czas.', 60),
    ('intestines', 'intestines', 'noun', 'the long tubes in the belly', 'jelita', 'The intestines digest food.', 'Jelita trawią jedzenie.', 61),
    ('bladder', 'bladder', 'noun', 'the organ that stores urine', 'pęcherz', 'The bladder is full.', 'Pęcherz jest pełny.', 62),
    ('blood', 'blood', 'noun', 'the red liquid in the body', 'krew', 'Blood carries oxygen.', 'Krew przenosi tlen.', 63),
    ('muscles', 'muscles', 'noun', 'tissues that make movement possible', 'mięśnie', 'Strong muscles help posture.', 'Silne mięśnie pomagają w postawie.', 64),
    ('bones', 'bones', 'noun', 'the hard framework of the body', 'kości', 'Bones protect the organs.', 'Kości chronią narządy.', 65),
    ('scalp', 'scalp', 'noun', 'the skin covering the head', 'skóra głowy', 'The scalp is sensitive.', 'Skóra głowy jest wrażliwa.', 66),
    ('temple', 'temple', 'noun', 'the side of the head near the eyes', 'skroń', 'He touched his temple.', 'Dotknął swojej skroni.', 67),
    ('eyebrow', 'eyebrow', 'noun', 'the line of hair above the eye', 'brew', 'Her eyebrow is arched.', 'Jej brew jest wygięta.', 68),
    ('eyelid', 'eyelid', 'noun', 'the skin that covers the eye', 'powieka', 'She closed her eyelid.', 'Zamknęła powiekę.', 69),
    ('eyelash', 'eyelash', 'noun', 'a hair on the edge of the eyelid', 'rzęsa', 'An eyelash fell into my eye.', 'Rzęsa wpadła mi do oka.', 70),
    ('jaw', 'jaw', 'noun', 'the lower part of the face for chewing', 'szczęka', 'He clenched his jaw.', 'Zacisnął szczękę.', 71),
    ('cheekbone', 'cheekbone', 'noun', 'the bone of the cheek', 'kość policzkowa', 'Her cheekbones are high.', 'Ma wysokie kości policzkowe.', 72),
    ('beard', 'beard', 'noun', 'hair growing on the chin', 'broda', 'He grew a beard.', 'Zapuścił brodę.', 73),
    ('moustache', 'moustache', 'noun', 'hair above the upper lip', 'wąsy', 'His moustache is neat.', 'Jego wąsy są zadbane.', 74),
    ('upper lip', 'upper lip', 'noun', 'the top lip of the mouth', 'górna warga', 'The upper lip is swollen.', 'Górna warga jest spuchnięta.', 75),
    ('lower lip', 'lower lip', 'noun', 'the bottom lip of the mouth', 'dolna warga', 'She bit her lower lip.', 'Przygryzła dolną wargę.', 76),
    ('rib', 'rib', 'noun', 'a bone that protects the chest', 'żebro', 'He bruised a rib.', 'Stłukł sobie żebro.', 77),
    ('ribcage', 'ribcage', 'noun', 'the set of ribs around the chest', 'klatka żebrowa', 'The ribcage protects the heart.', 'Klatka żebrowa chroni serce.', 78),
    ('spine', 'spine', 'noun', 'the backbone', 'kręgosłup', 'Keep your spine straight.', 'Trzymaj kręgosłup prosto.', 79),
    ('shoulder blade', 'shoulder blade', 'noun', 'the bone on the back of the shoulder', 'łopatka', 'He felt pain near his shoulder blade.', 'Poczuł ból w okolicy łopatki.', 80),
    ('collarbone', 'collarbone', 'noun', 'the bone between the shoulder and chest', 'obojczyk', 'She broke her collarbone.', 'Złamała obojczyk.', 81),
    ('abdomen', 'abdomen', 'noun', 'the belly area of the body', 'brzuch', 'The abdomen is tense.', 'Brzuch jest napięty.', 82),
    ('navel', 'navel', 'noun', 'the belly button', 'pępek', 'The baby has a navel.', 'Dziecko ma pępek.', 83),
    ('pelvis', 'pelvis', 'noun', 'the bony structure of the hips', 'miednica', 'The pelvis supports the spine.', 'Miednica podtrzymuje kręgosłup.', 84),
    ('forearm', 'forearm', 'noun', 'the part of the arm below the elbow', 'przedramię', 'He has a tattoo on his forearm.', 'Ma tatuaż na przedramieniu.', 85),
    ('upper arm', 'upper arm', 'noun', 'the part of the arm above the elbow', 'ramię', 'She stretched her upper arm.', 'Rozciągnęła ramię.', 86),
    ('palm', 'palm', 'noun', 'the inside of the hand', 'dłoń', 'He held it in his palm.', 'Trzymał to w dłoni.', 87),
    ('knuckle', 'knuckle', 'noun', 'the joint of a finger', 'knykieć', 'His knuckles are bruised.', 'Jego knykcie są posiniaczone.', 88),
    ('fingertip', 'fingertip', 'noun', 'the tip of a finger', 'opuszek palca', 'Use your fingertip.', 'Użyj opuszka palca.', 89),
    ('armpit', 'armpit', 'noun', 'the area under the shoulder', 'pacha', 'He has a rash in his armpit.', 'Ma wysypkę pod pachą.', 90),
    ('thumb', 'thumb', 'noun', 'the short thick finger', 'kciuk', 'He hurt his thumb.', 'Uraził kciuk.', 91),
    ('kneecap', 'kneecap', 'noun', 'the bone at the front of the knee', 'rzepka', 'She hit her kneecap.', 'Uderzyła rzepkę.', 92),
    ('shin', 'shin', 'noun', 'the front of the lower leg', 'goleń', 'He has a cut on his shin.', 'Ma skaleczenie na goleni.', 93),
    ('Achilles tendon', 'achilles tendon', 'noun', 'the tendon at the back of the ankle', 'ścięgno Achillesa', 'He injured his Achilles tendon.', 'Uszkodził ścięgno Achillesa.', 94),
    ('instep', 'instep', 'noun', 'the top of the foot', 'podbicie stopy', 'The instep is swollen.', 'Podbicie stopy jest spuchnięte.', 95),
    ('sole', 'sole', 'noun', 'the underside of the foot', 'podeszwa', 'The sole of my foot hurts.', 'Boli mnie podeszwa stopy.', 96),
    ('ball of the foot', 'ball of the foot', 'noun', 'the padded area under the toes', 'poduszka stopy', 'She stood on the ball of her foot.', 'Stanęła na poduszce stopy.', 97),
    ('big toe', 'big toe', 'noun', 'the largest toe', 'duży palec u stopy', 'He broke his big toe.', 'Złamał duży palec u stopy.', 98),
    ('little toe', 'little toe', 'noun', 'the smallest toe', 'mały palec u stopy', 'The little toe is bruised.', 'Mały palec u stopy jest posiniaczony.', 99),
    ('blemish', 'blemish', 'noun', 'a small mark on the skin', 'niedoskonałość', 'This blemish will fade.', 'Ta niedoskonałość zniknie.', 100),
    ('scar tissue', 'scar tissue', 'noun', 'tissue that forms after a wound', 'tkanka bliznowata', 'Scar tissue is stiff.', 'Tkanka bliznowata jest sztywna.', 101),
    ('burn', 'burn', 'noun', 'a wound caused by heat', 'oparzenie', 'The burn is painful.', 'Oparzenie jest bolesne.', 102),
    ('blister', 'blister', 'noun', 'a small bubble on the skin', 'pęcherz', 'A blister formed on his heel.', 'Na pięcie zrobił się pęcherz.', 103),
    ('swelling', 'swelling', 'noun', 'an enlarged area from injury', 'obrzęk', 'The swelling went down.', 'Obrzęk ustąpił.', 104),
    ('irritation', 'irritation', 'noun', 'a red or itchy reaction', 'podrażnienie', 'The cream reduced irritation.', 'Krem zmniejszył podrażnienie.', 105),
    ('redness', 'redness', 'noun', 'red color on the skin', 'zaczerwienienie', 'Redness appeared around the cut.', 'Wokół skaleczenia pojawiło się zaczerwienienie.', 106),
    ('stretch marks', 'stretch marks', 'noun', 'lines on the skin after stretching', 'rozstępy', 'Stretch marks can fade over time.', 'Rozstępy mogą z czasem zblednąć.', 107),
    ('flaky skin', 'flaky skin', 'noun', 'skin that peels in small pieces', 'łuszcząca się skóra', 'Flaky skin needs moisture.', 'Łuszcząca się skóra potrzebuje nawilżenia.', 108),
    ('spinal cord', 'spinal cord', 'noun', 'the nerve cord inside the spine', 'rdzeń kręgowy', 'The spinal cord sends signals.', 'Rdzeń kręgowy wysyła sygnały.', 109),
    ('ribs', 'ribs', 'noun', 'the bones around the chest', 'żebra', 'He felt pain in his ribs.', 'Czuł ból w żebrach.', 110),
    ('pancreas', 'pancreas', 'noun', 'the organ that produces insulin', 'trzustka', 'The pancreas helps digestion.', 'Trzustka wspiera trawienie.', 111),
    ('spleen', 'spleen', 'noun', 'the organ near the stomach', 'śledziona', 'The spleen filters blood.', 'Śledziona filtruje krew.', 112),
    ('gallbladder', 'gallbladder', 'noun', 'the organ that stores bile', 'pęcherzyk żółciowy', 'The gallbladder stores bile.', 'Pęcherzyk żółciowy magazynuje żółć.', 113),
    ('esophagus', 'esophagus', 'noun', 'the tube from mouth to stomach', 'przełyk', 'Food passes through the esophagus.', 'Jedzenie przechodzi przez przełyk.', 114),
    ('colon', 'colon', 'noun', 'the large intestine', 'okrężnica', 'The colon absorbs water.', 'Okrężnica wchłania wodę.', 115),
    ('small intestine', 'small intestine', 'noun', 'the long, thin intestine', 'jelito cienkie', 'The small intestine absorbs nutrients.', 'Jelito cienkie wchłania składniki odżywcze.', 116),
    ('large intestine', 'large intestine', 'noun', 'the wider part of the intestine', 'jelito grube', 'The large intestine absorbs water.', 'Jelito grube wchłania wodę.', 117),
    ('appendix', 'appendix', 'noun', 'a small pouch near the intestines', 'wyrostek robaczkowy', 'The appendix can get inflamed.', 'Wyrostek robaczkowy może się zapalić.', 118),
    ('diaphragm', 'diaphragm', 'noun', 'the muscle used for breathing', 'przepona', 'The diaphragm moves when you breathe.', 'Przepona porusza się podczas oddychania.', 119),
    ('veins', 'veins', 'noun', 'blood vessels that carry blood to the heart', 'żyły', 'Veins carry blood back.', 'Żyły odprowadzają krew.', 120),
    ('arteries', 'arteries', 'noun', 'blood vessels that carry blood from the heart', 'tętnice', 'Arteries carry blood out.', 'Tętnice odprowadzają krew z serca.', 121)
)
insert into lexicon_translations (sense_id, translation_pl)
select s.id, w.translation_pl
from words w
join lexicon_entries e on e.lemma_norm = w.lemma_norm and e.pos = w.pos
join lexicon_senses s on s.entry_id = e.id and s.sense_order = 0
where not exists (
  select 1 from lexicon_translations lt
  where lt.sense_id = s.id
);

with words(lemma, lemma_norm, pos, definition_en, translation_pl, example_en, example_pl, order_index) as (
  values
    ('head', 'head', 'noun', 'the upper part of the body', 'głowa', 'My head hurts today.', 'Dziś boli mnie głowa.', 1),
    ('face', 'face', 'noun', 'the front part of the head', 'twarz', 'Her face looks tired.', 'Jej twarz wygląda na zmęczoną.', 2),
    ('hair', 'hair', 'noun', 'the strands growing on the head', 'włosy', 'His hair is wet.', 'Jego włosy są mokre.', 3),
    ('forehead', 'forehead', 'noun', 'the part above the eyes', 'czoło', 'She touched her forehead.', 'Dotknęła swojego czoła.', 4),
    ('eye', 'eye', 'noun', 'the organ of sight', 'oko', 'My eye is red.', 'Moje oko jest czerwone.', 5),
    ('ear', 'ear', 'noun', 'the organ of hearing', 'ucho', 'He has an earache.', 'Ma ból ucha.', 6),
    ('nose', 'nose', 'noun', 'the organ used for breathing and smelling', 'nos', 'My nose is cold.', 'Mój nos jest zimny.', 7),
    ('mouth', 'mouth', 'noun', 'the opening used to eat and speak', 'usta', 'Open your mouth, please.', 'Otwórz usta, proszę.', 8),
    ('lip', 'lip', 'noun', 'the edge of the mouth', 'warga', 'She bit her lip.', 'Przygryzła wargę.', 9),
    ('cheek', 'cheek', 'noun', 'the side of the face', 'policzek', 'He kissed her cheek.', 'Pocałował ją w policzek.', 10),
    ('tooth', 'tooth', 'noun', 'a hard structure in the mouth', 'ząb', 'This tooth hurts.', 'Ten ząb boli.', 11),
    ('tongue', 'tongue', 'noun', 'the muscle in the mouth', 'język', 'He burned his tongue.', 'Oparzył sobie język.', 12),
    ('chin', 'chin', 'noun', 'the lower part of the face', 'broda', 'He has a strong chin.', 'Ma mocną brodę.', 13),
    ('facial hair', 'facial hair', 'noun', 'hair growing on the face', 'zarost', 'Facial hair grows fast.', 'Zarost rośnie szybko.', 14),
    ('torso', 'torso', 'noun', 'the main part of the body without limbs', 'tułów', 'The torso is strong.', 'Tułów jest silny.', 15),
    ('chest', 'chest', 'noun', 'the front of the upper body', 'klatka piersiowa', 'He felt pain in his chest.', 'Poczuł ból w klatce piersiowej.', 16),
    ('back', 'back', 'noun', 'the rear part of the body', 'plecy', 'My back is sore.', 'Bolą mnie plecy.', 17),
    ('neck', 'neck', 'noun', 'the part connecting head and body', 'szyja', 'She wears a scarf on her neck.', 'Nosi szalik na szyi.', 18),
    ('belly', 'belly', 'noun', 'the front of the body between chest and hips', 'brzuch', 'My belly feels full.', 'Mój brzuch jest pełny.', 19),
    ('waist', 'waist', 'noun', 'the narrow middle part of the body', 'talia', 'The belt sits on the waist.', 'Pasek leży na talii.', 20),
    ('hip', 'hip', 'noun', 'the side of the body above the leg', 'biodro', 'She hurt her hip.', 'Uraziła sobie biodro.', 21),
    ('shoulder', 'shoulder', 'noun', 'the joint connecting arm to body', 'bark', 'He carried the bag on his shoulder.', 'Niósł torbę na barku.', 22),
    ('arm', 'arm', 'noun', 'the upper limb from shoulder to hand', 'ramię', 'He raised his arm.', 'Podniósł ramię.', 23),
    ('elbow', 'elbow', 'noun', 'the joint in the middle of the arm', 'łokieć', 'She leaned on her elbow.', 'Oparła się na łokciu.', 24),
    ('wrist', 'wrist', 'noun', 'the joint between hand and arm', 'nadgarstek', 'He wears a watch on his wrist.', 'Nosi zegarek na nadgarstku.', 25),
    ('hand', 'hand', 'noun', 'the part at the end of the arm', 'dłoń', 'Wash your hands.', 'Umyj dłonie.', 26),
    ('finger', 'finger', 'noun', 'a digit on the hand', 'palec', 'He cut his finger.', 'Skaleczył palec.', 27),
    ('nail', 'nail', 'noun', 'the hard covering at the end of a finger', 'paznokieć', 'She painted her nails.', 'Pomalowała paznokcie.', 28),
    ('nipple', 'nipple', 'noun', 'the small part in the center of the breast', 'sutek', 'The baby touched the nipple.', 'Dziecko dotknęło sutka.', 29),
    ('breast', 'breast', 'noun', 'the part on the front of the chest', 'pierś', 'She felt pain in her breast.', 'Poczuła ból w piersi.', 30),
    ('leg', 'leg', 'noun', 'the limb used for walking', 'noga', 'My leg is tired.', 'Moja noga jest zmęczona.', 31),
    ('thigh', 'thigh', 'noun', 'the upper part of the leg', 'udo', 'He has strong thighs.', 'Ma mocne uda.', 32),
    ('knee', 'knee', 'noun', 'the joint between thigh and lower leg', 'kolano', 'She hurt her knee.', 'Uraziła kolano.', 33),
    ('calf', 'calf', 'noun', 'the back part of the lower leg', 'łydka', 'His calf cramped.', 'Złapał go skurcz łydki.', 34),
    ('ankle', 'ankle', 'noun', 'the joint between leg and foot', 'kostka', 'He twisted his ankle.', 'Skręcił kostkę.', 35),
    ('foot', 'foot', 'noun', 'the part you stand on', 'stopa', 'My foot is cold.', 'Moja stopa jest zimna.', 36),
    ('heel', 'heel', 'noun', 'the back part of the foot', 'pięta', 'Her heel hurts.', 'Boli ją pięta.', 37),
    ('toe', 'toe', 'noun', 'a digit on the foot', 'palec u stopy', 'He stubbed his toe.', 'Uderzył palcem u stopy.', 38),
    ('toenail', 'toenail', 'noun', 'the hard covering of a toe', 'paznokieć u stopy', 'He cut his toenail.', 'Obciął paznokieć u stopy.', 39),
    ('skin', 'skin', 'noun', 'the outer layer of the body', 'skóra', 'My skin is dry.', 'Moja skóra jest sucha.', 40),
    ('complexion', 'complexion', 'noun', 'the natural color of the skin', 'cera', 'Her complexion is clear.', 'Jej cera jest czysta.', 41),
    ('scar', 'scar', 'noun', 'a mark left after a wound', 'blizna', 'He has a small scar.', 'Ma małą bliznę.', 42),
    ('bruise', 'bruise', 'noun', 'a dark mark after a hit', 'siniak', 'The bruise is blue.', 'Siniak jest niebieski.', 43),
    ('cut', 'cut', 'noun', 'a small wound made by something sharp', 'skaleczenie', 'The cut is shallow.', 'Skaleczenie jest płytkie.', 44),
    ('scratch', 'scratch', 'noun', 'a thin mark on the skin', 'zadrapanie', 'The scratch is small.', 'Zadrapanie jest małe.', 45),
    ('rash', 'rash', 'noun', 'an area of irritated skin', 'wysypka', 'He has a rash on his arm.', 'Ma wysypkę na ramieniu.', 46),
    ('spot', 'spot', 'noun', 'a small mark on the skin', 'plamka', 'There is a spot on her cheek.', 'Na jej policzku jest plamka.', 47),
    ('pimple', 'pimple', 'noun', 'a small inflamed spot on the skin', 'pryszcz', 'A pimple appeared overnight.', 'Pryszcz pojawił się w nocy.', 48),
    ('wrinkle', 'wrinkle', 'noun', 'a small line on the skin', 'zmarszczka', 'Wrinkles appear with age.', 'Zmarszczki pojawiają się z wiekiem.', 49),
    ('freckle', 'freckle', 'noun', 'a small light-brown spot', 'pieg', 'She has freckles on her nose.', 'Ma piegi na nosie.', 50),
    ('mole', 'mole', 'noun', 'a small dark spot on the skin', 'pieprzyk', 'The mole is harmless.', 'Pieprzyk jest niegroźny.', 51),
    ('sweat', 'sweat', 'noun', 'the liquid from the skin when hot', 'pot', 'Sweat dripped from his face.', 'Pot kapał z jego twarzy.', 52),
    ('dirt', 'dirt', 'noun', 'soil or dust on the skin', 'brud', 'There is dirt on your hands.', 'Masz brud na rękach.', 53),
    ('brain', 'brain', 'noun', 'the organ that controls the body', 'mózg', 'The brain needs rest.', 'Mózg potrzebuje odpoczynku.', 54),
    ('throat', 'throat', 'noun', 'the passage in the neck', 'gardło', 'My throat is sore.', 'Boli mnie gardło.', 55),
    ('heart', 'heart', 'noun', 'the organ that pumps blood', 'serce', 'Her heart beats fast.', 'Jej serce bije szybko.', 56),
    ('lungs', 'lungs', 'noun', 'the organs used for breathing', 'płuca', 'The lungs need fresh air.', 'Płuca potrzebują świeżego powietrza.', 57),
    ('stomach', 'stomach', 'noun', 'the organ that digests food', 'żołądek', 'My stomach hurts.', 'Boli mnie żołądek.', 58),
    ('liver', 'liver', 'noun', 'the organ that processes nutrients', 'wątroba', 'The liver is important for health.', 'Wątroba jest ważna dla zdrowia.', 59),
    ('kidneys', 'kidneys', 'noun', 'the organs that filter blood', 'nerki', 'The kidneys work all the time.', 'Nerki pracują cały czas.', 60),
    ('intestines', 'intestines', 'noun', 'the long tubes in the belly', 'jelita', 'The intestines digest food.', 'Jelita trawią jedzenie.', 61),
    ('bladder', 'bladder', 'noun', 'the organ that stores urine', 'pęcherz', 'The bladder is full.', 'Pęcherz jest pełny.', 62),
    ('blood', 'blood', 'noun', 'the red liquid in the body', 'krew', 'Blood carries oxygen.', 'Krew przenosi tlen.', 63),
    ('muscles', 'muscles', 'noun', 'tissues that make movement possible', 'mięśnie', 'Strong muscles help posture.', 'Silne mięśnie pomagają w postawie.', 64),
    ('bones', 'bones', 'noun', 'the hard framework of the body', 'kości', 'Bones protect the organs.', 'Kości chronią narządy.', 65),
    ('scalp', 'scalp', 'noun', 'the skin covering the head', 'skóra głowy', 'The scalp is sensitive.', 'Skóra głowy jest wrażliwa.', 66),
    ('temple', 'temple', 'noun', 'the side of the head near the eyes', 'skroń', 'He touched his temple.', 'Dotknął swojej skroni.', 67),
    ('eyebrow', 'eyebrow', 'noun', 'the line of hair above the eye', 'brew', 'Her eyebrow is arched.', 'Jej brew jest wygięta.', 68),
    ('eyelid', 'eyelid', 'noun', 'the skin that covers the eye', 'powieka', 'She closed her eyelid.', 'Zamknęła powiekę.', 69),
    ('eyelash', 'eyelash', 'noun', 'a hair on the edge of the eyelid', 'rzęsa', 'A eyelash fell into my eye.', 'Rzęsa wpadła mi do oka.', 70),
    ('jaw', 'jaw', 'noun', 'the lower part of the face for chewing', 'szczęka', 'He clenched his jaw.', 'Zacisnął szczękę.', 71),
    ('cheekbone', 'cheekbone', 'noun', 'the bone of the cheek', 'kość policzkowa', 'Her cheekbones are high.', 'Ma wysokie kości policzkowe.', 72),
    ('beard', 'beard', 'noun', 'hair growing on the chin', 'broda', 'He grew a beard.', 'Zapuścił brodę.', 73),
    ('moustache', 'moustache', 'noun', 'hair above the upper lip', 'wąsy', 'His moustache is neat.', 'Jego wąsy są zadbane.', 74),
    ('upper lip', 'upper lip', 'noun', 'the top lip of the mouth', 'górna warga', 'The upper lip is swollen.', 'Górna warga jest spuchnięta.', 75),
    ('lower lip', 'lower lip', 'noun', 'the bottom lip of the mouth', 'dolna warga', 'She bit her lower lip.', 'Przygryzła dolną wargę.', 76),
    ('rib', 'rib', 'noun', 'a bone that protects the chest', 'żebro', 'He bruised a rib.', 'Stłukł sobie żebro.', 77),
    ('ribcage', 'ribcage', 'noun', 'the set of ribs around the chest', 'klatka żebrowa', 'The ribcage protects the heart.', 'Klatka żebrowa chroni serce.', 78),
    ('spine', 'spine', 'noun', 'the backbone', 'kręgosłup', 'Keep your spine straight.', 'Trzymaj kręgosłup prosto.', 79),
    ('shoulder blade', 'shoulder blade', 'noun', 'the bone on the back of the shoulder', 'łopatka', 'He felt pain near his shoulder blade.', 'Poczuł ból w okolicy łopatki.', 80),
    ('collarbone', 'collarbone', 'noun', 'the bone between the shoulder and chest', 'obojczyk', 'She broke her collarbone.', 'Złamała obojczyk.', 81),
    ('abdomen', 'abdomen', 'noun', 'the belly area of the body', 'brzuch', 'The abdomen is tense.', 'Brzuch jest napięty.', 82),
    ('navel', 'navel', 'noun', 'the belly button', 'pępek', 'The baby has a navel.', 'Dziecko ma pępek.', 83),
    ('pelvis', 'pelvis', 'noun', 'the bony structure of the hips', 'miednica', 'The pelvis supports the spine.', 'Miednica podtrzymuje kręgosłup.', 84),
    ('forearm', 'forearm', 'noun', 'the part of the arm below the elbow', 'przedramię', 'He has a tattoo on his forearm.', 'Ma tatuaż na przedramieniu.', 85),
    ('upper arm', 'upper arm', 'noun', 'the part of the arm above the elbow', 'ramię', 'She stretched her upper arm.', 'Rozciągnęła ramię.', 86),
    ('palm', 'palm', 'noun', 'the inside of the hand', 'dłoń', 'He held it in his palm.', 'Trzymał to w dłoni.', 87),
    ('knuckle', 'knuckle', 'noun', 'the joint of a finger', 'knykieć', 'His knuckles are bruised.', 'Jego knykcie są posiniaczone.', 88),
    ('fingertip', 'fingertip', 'noun', 'the tip of a finger', 'opuszek palca', 'Use your fingertip.', 'Użyj opuszka palca.', 89),
    ('armpit', 'armpit', 'noun', 'the area under the shoulder', 'pacha', 'He has a rash in his armpit.', 'Ma wysypkę pod pachą.', 90),
    ('thumb', 'thumb', 'noun', 'the short thick finger', 'kciuk', 'He hurt his thumb.', 'Uraził kciuk.', 91),
    ('kneecap', 'kneecap', 'noun', 'the bone at the front of the knee', 'rzepka', 'She hit her kneecap.', 'Uderzyła rzepkę.', 92),
    ('shin', 'shin', 'noun', 'the front of the lower leg', 'goleń', 'He has a cut on his shin.', 'Ma skaleczenie na goleni.', 93),
    ('Achilles tendon', 'achilles tendon', 'noun', 'the tendon at the back of the ankle', 'ścięgno Achillesa', 'He injured his Achilles tendon.', 'Uszkodził ścięgno Achillesa.', 94),
    ('instep', 'instep', 'noun', 'the top of the foot', 'podbicie stopy', 'The instep is swollen.', 'Podbicie stopy jest spuchnięte.', 95),
    ('sole', 'sole', 'noun', 'the underside of the foot', 'podeszwa', 'The sole of my foot hurts.', 'Boli mnie podeszwa stopy.', 96),
    ('ball of the foot', 'ball of the foot', 'noun', 'the padded area under the toes', 'poduszka stopy', 'She stood on the ball of her foot.', 'Stanęła na poduszce stopy.', 97),
    ('big toe', 'big toe', 'noun', 'the largest toe', 'duży palec u stopy', 'He broke his big toe.', 'Złamał duży palec u stopy.', 98),
    ('little toe', 'little toe', 'noun', 'the smallest toe', 'mały palec u stopy', 'The little toe is bruised.', 'Mały palec u stopy jest posiniaczony.', 99),
    ('blemish', 'blemish', 'noun', 'a small mark on the skin', 'niedoskonałość', 'This blemish will fade.', 'Ta niedoskonałość zniknie.', 100),
    ('scar tissue', 'scar tissue', 'noun', 'tissue that forms after a wound', 'tkanka bliznowata', 'Scar tissue is stiff.', 'Tkanka bliznowata jest sztywna.', 101),
    ('burn', 'burn', 'noun', 'a wound caused by heat', 'oparzenie', 'The burn is painful.', 'Oparzenie jest bolesne.', 102),
    ('blister', 'blister', 'noun', 'a small bubble on the skin', 'pęcherz', 'A blister formed on his heel.', 'Na pięcie zrobił się pęcherz.', 103),
    ('swelling', 'swelling', 'noun', 'an enlarged area from injury', 'obrzęk', 'The swelling went down.', 'Obrzęk ustąpił.', 104),
    ('irritation', 'irritation', 'noun', 'a red or itchy reaction', 'podrażnienie', 'The cream reduced irritation.', 'Krem zmniejszył podrażnienie.', 105),
    ('redness', 'redness', 'noun', 'red color on the skin', 'zaczerwienienie', 'Redness appeared around the cut.', 'Wokół skaleczenia pojawiło się zaczerwienienie.', 106),
    ('stretch marks', 'stretch marks', 'noun', 'lines on the skin after stretching', 'rozstępy', 'Stretch marks can fade over time.', 'Rozstępy mogą z czasem zblednąć.', 107),
    ('flaky skin', 'flaky skin', 'noun', 'skin that peels in small pieces', 'łuszcząca się skóra', 'Flaky skin needs moisture.', 'Łuszcząca się skóra potrzebuje nawilżenia.', 108),
    ('spinal cord', 'spinal cord', 'noun', 'the nerve cord inside the spine', 'rdzeń kręgowy', 'The spinal cord sends signals.', 'Rdzeń kręgowy wysyła sygnały.', 109),
    ('ribs', 'ribs', 'noun', 'the bones around the chest', 'żebra', 'He felt pain in his ribs.', 'Czuł ból w żebrach.', 110),
    ('pancreas', 'pancreas', 'noun', 'the organ that produces insulin', 'trzustka', 'The pancreas helps digestion.', 'Trzustka wspiera trawienie.', 111),
    ('spleen', 'spleen', 'noun', 'the organ near the stomach', 'śledziona', 'The spleen filters blood.', 'Śledziona filtruje krew.', 112),
    ('gallbladder', 'gallbladder', 'noun', 'the organ that stores bile', 'pęcherzyk żółciowy', 'The gallbladder stores bile.', 'Pęcherzyk żółciowy magazynuje żółć.', 113),
    ('esophagus', 'esophagus', 'noun', 'the tube from mouth to stomach', 'przełyk', 'Food passes through the esophagus.', 'Jedzenie przechodzi przez przełyk.', 114),
    ('colon', 'colon', 'noun', 'the large intestine', 'okrężnica', 'The colon absorbs water.', 'Okrężnica wchłania wodę.', 115),
    ('small intestine', 'small intestine', 'noun', 'the long, thin intestine', 'jelito cienkie', 'The small intestine absorbs nutrients.', 'Jelito cienkie wchłania składniki odżywcze.', 116),
    ('large intestine', 'large intestine', 'noun', 'the wider part of the intestine', 'jelito grube', 'The large intestine absorbs water.', 'Jelito grube wchłania wodę.', 117),
    ('appendix', 'appendix', 'noun', 'a small pouch near the intestines', 'wyrostek robaczkowy', 'The appendix can get inflamed.', 'Wyrostek robaczkowy może się zapalić.', 118),
    ('diaphragm', 'diaphragm', 'noun', 'the muscle used for breathing', 'przepona', 'The diaphragm moves when you breathe.', 'Przepona porusza się podczas oddychania.', 119),
    ('veins', 'veins', 'noun', 'blood vessels that carry blood to the heart', 'żyły', 'Veins carry blood back.', 'Żyły odprowadzają krew.', 120),
    ('arteries', 'arteries', 'noun', 'blood vessels that carry blood from the heart', 'tętnice', 'Arteries carry blood out.', 'Tętnice odprowadzają krew z serca.', 121)
)
insert into lexicon_examples (sense_id, example_en, example_pl, source)
select s.id, w.example_en, w.example_pl, 'manual'
from words w
join lexicon_entries e on e.lemma_norm = w.lemma_norm and e.pos = w.pos
join lexicon_senses s on s.entry_id = e.id and s.sense_order = 0
where not exists (
  select 1 from lexicon_examples le
  where le.sense_id = s.id and le.example_en = w.example_en
);

commit;
